### ISSUE TITLE
RSA-OAEP with SHA-384

### ISSUE THREAD

**Issue by saulshanabrook** [vibornoff/webcrypto-shim#10]
Would it be possible to support generating/importing/exporting RSA-OAEP with SHA-384 for the hashing? I am happy to make a PR if you think it would be possible.

**Comment by vibornoff** [comment]
Short answer is "No".

[RFC 7518](https://tools.ietf.org/html/rfc7518) provides RSA-OAEP with SHA-1 and SHA-256 (both for hashing and MGF1). Moreover, it is some sort of cross-browser issue as Safari knows nothing about RSA-OAEP/SHA-256.

So if you want your webapp to be compatible with as much browsers as possible you should use RSA-OAEP with SHA-1.
