### ISSUE TITLE
Relation to asmcrypto

### ISSUE THREAD

**Issue by tererecool** [vibornoff/webcrypto-shim#2]
How is this project related to asmwebcrypto? If I use this I don't need the other? I know the asm lib can be used e.g. to do a pbkdf2 on MS Edge because it does not support this yet. If I now use this shim for IE11 would I still need the other lib for key derivation or? Could you please explain the differencea between the two projects and im what cases I should use one or the other?

**Comment by vibornoff** [comment]
asmwebcrypto? google says nothing about it. did you mean asmcrypto?

webcrypto-shim is completely independent project aimed to fix buggy/prefixed webcrypto implementations from IE11 and Safari. It small and has minimum of dependencies and doesn't require any external crypto libraries. In turn it doesn't provide any crypto features except those already implemented in your current browser's webcrypto api — it only adapts api to newer version of webcrypto spec.

If you need PBKDF2 on IE11 you have to get another lib.
