### ISSUE TITLE
Unsupported algorithm 'hmac' -- Safari

### ISSUE THREAD

**Issue by lightninglu10** [vibornoff/webcrypto-shim#20]
I'm trying to use this package to fix Safari's webcrypto but getting

```Unsupported algorithm 'hmac'```

I've included asymcrypto and elliptic in my html:

```
    <script src="%PUBLIC_URL%/webcrypto.shim.js"></script>
    <script src="%PUBLIC_URL%/asmcrypto.min.js"></script>
    <script src="%PUBLIC_URL%/elliptic.min.js"></script>
```

Any advice here?

**Comment by vibornoff** [comment]
Can you please make a complete code example (e.g. with https://jsfiddle.com)?

**Comment by Ruffio** [comment]
@lightninglu10 how about that code sample that demonstrates the issue?

**Comment by Ruffio** [comment]
@lightninglu10 how about that code sample that demonstrates the issue?
