### ISSUE TITLE
importKey RSA-OAEP with SHA-1 not working on safari 11

### ISSUE THREAD

**Issue by OriAmir** [vibornoff/webcrypto-shim#22]
Hey , I try to use 'importkey' on safari 11 and also on outlook for mac and both I get error.
`  window.crypto.subtle.importKey(
                        "jwk",
                        {
                            "kty": "RSA",
                            "e": difensoPublicKeyE,
                            "n": difensoPublicKeyN,
                            "alg": "RSA-OAEP",
                            "ext": true
                        },
                        {   /
                            name: "RSA-OAEP",
                            hash: { name: "SHA-1" },
                        },
                        true, 
                        ["encrypt"]
                        ).then(function (publicKey) {`

Then I get this error:
**OpeartionTypeError: Member JsonWebKey.kty is required and must be an instance of DOMString**

Not matter what I try it's same error... maybe someone can help please?

Thx

**Comment by vibornoff** [comment]
Does it still actual?
Could you please make a complete copy'n'paste-capable code example?

**Comment by Ruffio** [comment]
@OriAmir can you provide an example of your issue? Maybe use JSBin or similar?

**Comment by Ruffio** [comment]
@OriAmir and example?

**Comment by OriAmir** [comment]
@Ruffio I don't work on this project anymore so I don't know if something change  .. you try this?

**Comment by Ruffio** [comment]
This was fixed with: https://github.com/vibornoff/webcrypto-shim/commit/ae3e9fa3ad0cf24748c9025085b4883ba8ed0038#diff-f9277148bdb6cb3b8f35c2f847e04e6e

Is was the same issue and fixed that was used here: https://github.com/ipfs/js-ipfs/issues/995

This issue can be closed :-)
