### ISSUE TITLE
TypeError: Attempted to assign to readonly property.

### ISSUE THREAD

**Issue by miguelmota** [vibornoff/webcrypto-shim#23]
Safari error

<img width="556" alt="screen shot 2017-10-11 at 9 14 18 am" src="https://user-images.githubusercontent.com/168240/31452805-e961c304-ae64-11e7-80ca-6d12fab1bf05.png">
<img width="894" alt="screen shot 2017-10-11 at 9 14 25 am" src="https://user-images.githubusercontent.com/168240/31452809-eaa1b45e-ae64-11e7-9ff7-ebf8640e812a.png">

**Comment by StefanStadler** [comment]
I encountered the same issue with Safari 11 release
in Safari 10 it works as expected

**Comment by akselnordal** [comment]
Safari 11 should be standards compliant regarding the WebCrypto interfaces and not in need of `webcrypto-shim`. The feature tests should be updated to not eval the shim code for Safari 11

More info:
https://webkit.org/blog/7790/update-on-web-cryptography/

**Comment by vibornoff** [comment]
@miguelmota , make sure you're using the latest version.
