### ISSUE TITLE
Android 4.4 with Chrome 63

### ISSUE THREAD

**Issue by jwillmer** [vibornoff/webcrypto-shim#31]
I use browserstack to test my website and I found out that your polyfill is not working for Android 4.4 with Chrome 63. It returns at https://github.com/vibornoff/webcrypto-shim/blob/c11ecbbabca74e0321c1aff66457d96990935a58/webcrypto-shim.js#L28

This is the project: [emergency-contacts](https://github.com/jwillmer/emergency-contacts)

**Comment by vibornoff** [comment]
That's because since _Chrome for Android 44_ there is no need in the polyfill.

**Comment by jwillmer** [comment]
Oh, I should have mentioned that after this it breaks at 
` const pwHash = await crypto.subtle.digest('SHA-256', pwUtf8);` [link](https://github.com/jwillmer/emergency-contacts/blob/5d399317619bbf38eced06ab6556bb7e6b8b91b8/js/main.js#L49)

With the error: `TypeError: Cannot read property 'digest' of undefined`

**Comment by vibornoff** [comment]
Did you run the code from an insecure origin?
WebCrypto requires your code to be run from either localhost or https://...

**Comment by jwillmer** [comment]
That was the problem. Now it works, thx for the support!
