### ISSUE TITLE
Support for RSASSA-PKCS1-v1_5 signing SHA-512 on IE11

### ISSUE THREAD

**Issue by kenny128** [vibornoff/webcrypto-shim#36]
So im aware that RSASSA-PKCS1-v1_5 signing with SHA-512 isnt supported but I'm just wondering what needs to go into getting it to work. Is there a reason why it isn't support on this and many other shims and polyfills?

**Comment by vibornoff** [comment]
@kenny128 it's not implemented under the hood of IE crypto
