### ISSUE TITLE
Is it possible to use this shim on up-to-date browsers with non-https origins?

### ISSUE THREAD

**Issue by zachsa** [vibornoff/webcrypto-shim#39]
Hi,

I'm trying to use this shim so that I have access to `window.crypto.subtle` in an up-to-date version of chrome, but that is served from a non-https origin (i.e. a deployed development environment). Is this possible?

It looks like I am able to load the code:

```js
import('//jspm.dev/webcrypto-shim').then(mdl => console.log(mdl))
```

But in my chrome console, after doing that I still don't have access to the `window.crypto.subtle` object. I know that the reason that I DON'T have the object on my non-https environment is that Chrome explicitly prevents it. I was hoping I could use this shim in such an environment. 

Is that possible?

**Comment by gavinhenderson** [comment]
@zachsa Did you manage to get a solution for this? I am trying to do the same thing

**Comment by vibornoff** [comment]
@zachsa @gavinhenderson No, shim relies to underlying `window.crypto.subtle` that actually does the heavy lifting.
