### ISSUE TITLE
Npm Support

### ISSUE THREAD

**Issue by jcmei** [vibornoff/webcrypto-shim#4]
Have you considered publishing this shim to npm?  I am working on project that uses npm for browser dependencies, and I would like to include your shim as a dependency.

I've included a link to another project that ended up publishing to npm, as they discuss the reasons for publishing to npm better than I could.

[https://github.com/coolaj86/unibabel-js/issues/7](https://github.com/coolaj86/unibabel-js/issues/7)

Thanks.

**Comment by vibornoff** [comment]
Done. The minor issue is how to point that this is not a node.js module and it's especially designed to run in a browser.
